name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    branches: ["main"]

jobs:
  tagged-release:
    name: "Tagged Release"
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: "ubuntu-latest"
    timeout-minutes: 45

    steps:
      - name: Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Make
        run: make

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./release/*
